config/routes.rb
Glass::Application.routes.draw do

  get  "/location", to:"pages#location"
  get  "/terms", to:"pages#terms"
  get  "/returns", to:"pages#returns"
  get  "/about", to:"pages#about"
  get  "/index", to:"pages#index"
  get  "/contact", to:"pages#contact"
  get  "/brands", to:"pages#brands"
  match  "/newsletter", to:"pages#newsletter", via: [:get,:post]
  match "/newsletterSave", to:"pages#newsletterSave", via:[:post]

  match "/admin/NewsReport" ,to:"admin#newsletterReport", via: :get , as: 'NewsReport'
  match "/admin", to:"admin#index", via: :get
  match "/admin/Eaboutme", to:"admin#Eaboutme", via: [:get,:post], as:'mcms'
  match "/admin/EaboutmeSave", to:"admin#EaboutmeSave", via: :post
  match "/admin/Cbimage", to:"admin#Cbimage", via: [:get,:post,:patch]
  match "/admin/EditContact", to:"admin#EditContact", via: [:get,:post,:patch]
  match "/admin/Edit", to:"admin#EdirTermsOfService", via: [:get,:post,:patch]
  get "/admin/clear", to:"admin#clearNews"

  devise_for :users
  root 'pages#index'

end

app/models/mcms.rb
class Mcms < ActiveRecord::Base

  mount_uploader :pic1, AddpicassetUploader
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base

  # :name, :mail
  email_regex =/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name,presence: true, length:{maximum:50}
  validates :mail,presence: true ,format: {with:email_regex} , uniqueness: {case_sensitive: false}



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_action :authenticate_user!
  def index


  end

  def Eaboutme


         @bodyy= Mcms.first.body
         #render layout: false



  end

  def EdirTermsOfService
    @mcms = Mcms.first
    #initialize
    @mcms.canccelation= "EMPTY" if @mcms.canccelation.nil?
    @mcms.complaints = "EMPTY" if  @mcms.complaints.nil?
    @mcms.payment = "EMPTY" if     @mcms.payment.nil?
    @mcms.returnE= "EMPTY" if      @mcms.returnE.nil?
    @mcms.shippingp = "EMPTY" if   @mcms.shippingp.nil?
    @mcms.saboutus = "EMPTY" if    @mcms.saboutus.nil?
    @mcms.iphone= "EMPTY" if       @mcms.iphone.nil?
    @mcms.imail = "EMPTY" if       @mcms.imail.nil?
    @mcms.iaddress = "EMPTY" if    @mcms.iaddress.nil?


    if(Mcms.first.present?)
      if(request.patch?)

        @mcms.canccelation= params[:mcms][:canccelation] if params[:mcms][:canccelation].present?
        @mcms.complaints = params[:mcms][:complaints] if params[:mcms][:complaints].present?
        @mcms.payment = params[:mcms][:payment] if params[:mcms][:payment].present?
        @mcms.returnE= params[:mcms][:returnE] if params[:mcms][:returnE].present?
        @mcms.shippingp = params[:mcms][:shippingp] if params[:mcms][:shippingp].present?
        @mcms.saboutus = params[:mcms][:saboutus] if params[:mcms][:saboutus].present?



        @mcms.save!
        redirect_to admin_path



      end
    end
    end

  def EditContact
    @mcms = Mcms.first
    if(Mcms.first.present?)
    if(request.patch?)

      @mcms.imail= params[:mcms][:email] if params[:mcms][:email].present?
      @mcms.iaddress = params[:mcms][:address] if params[:mcms][:address].present?
      @mcms.iphone = params[:mcms][:phone] if params[:mcms][:phone].present?



      @mcms.save!
      redirect_to admin_path

    end

    end

  end

  def EaboutmeSave

    row = Mcms.first
    if(row.body.nil?)
      row.body = "EMPTY!!"
      row.save
    end
    row.body = params[:post][:body]
    row.save
   redirect_to admin_path


  end

  def newsletterReport

    @reports = Newsletter.all
      respond_to do |format|
      format.html # don't forget if you pass html
      format.xls { send_data(@reports.to_xls) }
        end


  end


  def Cbimage

   # Rails.logger.debug  "debugging -->"+params[:mcms][:pic2].inspect.to_s
    @mcms = Mcms.first


# Set location path in the database :
    if(@mcms[:pic1].nil?)
      @mcms[:pic1] ="app/assets/images/pic1/"
      @mcms.save
    end
    if(@mcms[:pic2].nil?)
      @mcms[:pic2] ="app/assets/images/sliders/"
      @mcms.save
    end
    if(@mcms[:pic3].nil?)
      @mcms[:pic3] ="app/assets/images/Brands/"
      @mcms.save
    end

if (request.patch?)


    #It uploads the banner pictures
   if(params[:mcms])
     FileUtils.rm_rf(Dir.glob("#{@mcms[:pic1].to_s}*" ))
     @topBanner = params[:mcms][:pic1]
       uploader = AddpicassetUploader.new(name:"topBanner" ,path:"#{@mcms[:pic1].to_s}")
       uploader.store!(@topBanner)
    end

    if(params[:post_attachments])
      FileUtils.rm_rf(Dir.glob("#{@mcms[:pic2].to_s}*" ))
      sliders = params[:post_attachments][:pic2]
      i=0
      while i < sliders.size  do
        uploader = AddpicassetUploader.new(name:"slider#{i}"+Time.now.to_s.gsub(/[\W]/,''),path:"#{@mcms[:pic2].to_s}")
        uploader.store!(sliders.at(i))
        i=i+1
      end







    end
    if(params[:mbrands])
      FileUtils.rm_rf(Dir.glob("#{@mcms[:pic3].to_s}*" ))
      sliders = params[:mbrands][:pic3]
      i=0
      while i < sliders.size  do
        uploader = AddpicassetUploader.new(name:"slider#{i}"+Time.now.to_s.gsub(/[\W]/,''),path:"#{@mcms[:pic3].to_s}")
        uploader.store!(sliders.at(i))
        i=i+1
      end

    end


    redirect_to admin_path

    end
  end

def clearNews

  Newsletter.delete_all
  redirect_to admin_path
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
require 'Aeditor'
class PagesController < ApplicationController

def index

  @AllSliders = Dir.glob("app/assets/images/Sliders/*.jpg")
end
  def location
  end

  def terms
    @record= Mcms.first
  end

  def about
  @record= Mcms.first
  end

def newsletter
  @newsletter = Newsletter.new
  render :layout => false

end


  def newsletterSave



    Newsletter.create(name: params[:newsletter][:name], mail: params[:newsletter][:mail])
    logger.debug(@newsletter.inspect.to_s)
    redirect_to action: 'index'

    end

  def brands

    @AllBrands = Dir.glob("app/assets/images/Brands/*.{jpg,png,gif,jpeg}")


  end

end

app/controllers/registrations_controller.rb
 # class RegistrationsController < Devise::RegistrationsController
  #  def new
   #   flash[:info] = 'Registrations are not open yet, but please check back soon'
    #  redirect_to root_path
    #end

   # def create
    #  flash[:info] = 'Registrations are not open yet, but please check back soon'
    #  redirect_to root_path
    #end
 # end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/Cbimage.html.erb
<div id="banner-wrapper">
  <div id="banner-container">
    <%= form_for @mcms,  url: admin_Cbimage_path , :html => {:multipart => true} do |f| %>
        <p>
            <h1><%= f.label "Edit Top Banner Image:" %></h1>
           <%= f.file_field :pic1 %>
        </p><br>

        <p>
            <h1><%= f.label "Edit Slider Image(s):" %></h1>
            <%= f.file_field :pic2, :multiple => true, name: "post_attachments[pic2][]" %>
        </p><br>

        <p>
            <h1><%= f.label "Edit Brand(s)" %></h1>
            <%= f.file_field :pic3, :multiple => true, name: "mbrands[pic3][]" %>
        </p>

        <p><br>
            <%= f.submit "Save"%>
        </p>

    <% end %>

      <%= link_to 'Back to Panel', admin_path %>
  </div>
</div>

app/views/admin/Eaboutme.html.erb
<div id="about-edit-wrapper">
  <div id="about-edit-container">

    <h1> EDIT ABOUT ME </h1>

    <%= form_tag('/admin/EaboutmeSave') do -%>

        <%=text_area(:post, :body, cols: 100, rows: 25,value:@bodyy) %></br>
        <div><%= submit_tag 'Save' %></div>

    <% end -%>

    <%= link_to 'Back to Panel', admin_path %>

    </div>
</div>

app/views/admin/EdirTermsOfService.html.erb
<div id="tos-wrapper">
  <div id="tos-container">
    <%= form_for @mcms ,url: admin_Edit_path do |f| %>
        <li>
          <%= f.label "ABOUT US:" %><br>
          <%= f.text_area :saboutus, value:@mcms.saboutus, size:"35" %>
        </li>

        <li>
          <%= f.label "Payment :" %><br>
          <%= f.text_area :payment, value:@mcms.payment, size:"35" %>
        </li>

        <li>
          <%= f.label "Shipping Policies :" %><br>
          <%= f.text_area :shippingp, value:@mcms.shippingp, size:"35" %>
        </li>

        <li>
          <%= f.label "Returns and Exchanges :" %><br>
          <%= f.text_area :returnE, value:@mcms.returnE, size:"35" %>
        </li>

        <li>
          <%= f.label "Cancellation :" %><br>
          <%= f.text_area :canccelation, value:@mcms.canccelation, size:"35" %>
        </li>

        <li>
          <%= f.label "Complaints :" %><br>
          <%= f.text_area :complaints, value:@mcms.complaints, size:"35" %>
        </li>



        <div id="save-box"><%=f.submit "save" %></div>
    <% end %>
  </div>
  <%= link_to 'Back to Panel', admin_path %>

</div>

app/views/admin/EditContact.html.erb
<div id="contact-wrapper">
  <div id="contact-container">
        <%= form_for @mcms ,url: admin_EditContact_path do |f| %>
            <li>
                <%= f.label "Telephone:" %><br>
                <%= f.text_field :phone, value:@mcms.iphone, size:"35" %>
            </li>

            <li>
                <%= f.label "Address:" %><br>
                <%= f.text_field :address, value:@mcms.iaddress, size:"35" %>
            </li>

            <li>
                <%= f.label "Email :" %><br>
                <%= f.text_field :email, value:@mcms.imail, size:"35" %>
            </li>

           <div id="save-box"><%=f.submit "save" %></div>
        <% end %>
    </div>
  <%= link_to 'Back to Panel', admin_path %>

</div>

app/views/admin/index.html.erb
<%= javascript_include_tag "application" %>
<div id="backend-wrapper">
  <div id="backend-container">
    <div id="backend-menu"><%= link_to"Edit Terms", controller: "admin", action: "EdirTermsOfService" %></div>
    <div id="backend-menu"><%= link_to"View Subscriptions", controller: "admin", action: "newsletterReport" %></div>
    <div id="backend-menu"><%= link_to "Edit About ME" ,controller: "admin", action: "Eaboutme" %></div>
    <div id="backend-menu"><%= link_to "Edit Contact Details" ,controller: "admin", action: "EditContact" %></div>
    <div id="backend-menu"><%= link_to "Edit Banner Images", controller: "admin", action: "Cbimage" %></div>
    <div id="backend-menu"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></div>
  </div>
</div>

app/views/admin/newsletterReport.html.erb
<div id="newsletter-wrapper">
  <div id="newsletter-container">

    <% @reports.each do |report| %>
        <h1><%= report[:name]%></h1><h2><%= report[:mail] %></h2>
    <% end %>

    <br><br>
    <%= link_to 'Export as Excel ', "NewsReport.xls" %><br>
    <%= link_to 'Back to Panel', admin_path %>
    <%= link_to 'Clear ALL', admin_clear_path %>


  </div>
</div>

app/views/layouts/_footer.html.erb

<div id="footer">
    <ul>
      <li><%= link_to "LOCATION", location_path %></li>
      <li>|</li>
      <li><%= link_to "CONTACT", terms_path+"?4" %></li>
      <li>|</li>
      <li><%= link_to "TERMS OF SERVICE", terms_path+"?3" %></li>
      <li>|</li>
      <li><%= link_to "RETURNS AND EXCHANGES", terms_path+"?2" %></li>
      <li>|</li>
      <li><%= link_to "ABOUT US", terms_path+"?1" %></li>
    </ul>

  <div id="extra-contact">Trendy Sunglasses <br> (310)123-1234 <br> 1234 Main St. <br> Santa Monica, CA <br> 90405</div>
</div>


app/views/layouts/_header.html.erb

<div id="iconposition">
  <a href="https://www.facebook.com/trendysm" target="_blank"><div id="socialicon"><%= image_tag"facebook.png" %></div></a>
  <a href="https://www.instagram.com/" target="_blank"><div id="socialicon"><%= image_tag"instagram.png" %></div></a>
  <a href="https://twitter.com/trendy_sunglass" target="_blank"><div id="socialicon"><%= image_tag"twitter.png" %></div></a>
</div>

<header>
  <a href="/"><div id ="logo"></div></a>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
</header>

<nav class="clearfix">
  <ul class="clearfix">
    <li><%= link_to "HOME", root_path %></li>
    <li><%= link_to "BRANDS", brands_path %></li>
    <li><%= link_to "ABOUT" , about_path %></li>
    <li><%= link_to "LOCATION", location_path %></li>
  </ul>

  <a href="#" id="pull">MENU</a>
</nav>




app/views/layouts/_styles.html.erb
<%= stylesheet_link_tag    "application", media: "all" %>

<%= javascript_include_tag "jquery.js" %>
<%= javascript_include_tag "responsive" %>
<%= javascript_include_tag "sroller" %>
<%= javascript_include_tag "http://cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.1.47/jquery.form-validator.min.js" %>




app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Glass</title>

  <%= csrf_meta_tags %>
  <%= render "layouts/styles"%>
</head>
<body >

<div id="popi"></div>
<div id="wrapper">

    <%= render "layouts/header"%>
    <%= yield %>

    <%= render "layouts/footer"%>


</div>

</body>
</html>

app/views/pages/about.html.erb
<div id="about-wrapper">
  <div id="about-paragraph">
    <div id="about">ABOUT</div>
    <%= @record.body.html_safe %>
  </div>
</div>

app/views/pages/brands.html.erb

<div id="sun-text">
  Brands
</div>

<div id="brands-wrapper">
    <div id="brands-container">
        <%  @AllBrands.each_with_index do |item, index| %>
            <div id="brand<%=index%3+1 %>">
                <%= image_tag "#{item.gsub("app/assets/images/", "")}"%>
            </div>
        <% end  %>
    </div>
</div>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/index.html.erb
<%= javascript_include_tag "yelp" %>
<%= javascript_include_tag "lean-slider" %>
<%= javascript_include_tag "popUp" %>
<div id="top-banner">
  <div id="top-banner-text-large">
    MENTION THIS AD AND SAVE 20%! | (310) 392-0055
  </div>


</div>

<div id="content1">
  <div id="gallery">
    <div class="slider-container">
      <div class="slider-wrapper">
        <div id="slider">

          <%  @AllSliders.each do |item| %>
              <%= image_tag "#{item.gsub("app/assets/images/", "")}"%>
          <% end %>

        </div>
        <div id="slider-direction-nav"></div>
        <div id="slider-control-nav"></div>
      </div>
    </div>
  </div>
</div>

<div id="mail-list" >
  <div id="mail-text"></div>
</div>

<div id="box-center">
    <div id='yelpwidget'></div>
    <div id="yelp-logo"></div>
</div>

<a href="https://www.facebook.com/trendysm" target="_blank"><div id="box-right-top"></div></a>
<a href="https://www.instagram.com/" target="_blank"><div id="box-right-center"></div></a>
<a href="https://twitter.com/trendy_sunglass" target="_blank"><div id="box-right-bottom"></div></a>

<script>

</script>

app/views/pages/location.html.erb
<div id="come_visit">
  Come Visit Us!
</div>

<div id="map-wrapper">
    <div id="map-canvas">
        <iframe width=100% height=100% frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?t=m&amp;q=Trendy+Sunglasses,+Santa+Monica,+CA&amp;ie=UTF8&amp;hq=Trendy+Sunglasses,+Santa+Monica,+CA&amp;ll=34.0015
,-118.483&amp;spn=0.006295,0.006295&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com/maps?t=m&amp;q=Trendy+Sunglasses,+Santa+Monica,+CA&amp;ie=UTF8&amp;hq=Trendy+Sunglasses,+Santa+Monica,+CA&amp;ll=34.0005,-118.482335&amp;spn=0.006295,0.006295&amp;source=embed" style="color:#000;text-align:left">View Larger Map</a></small>
    </div>
</div>

app/views/pages/newsletter.html.erb

<%= form_for @newsletter, url: {action: "newsletterSave"}, html: {class: "nifty_form"} do |f| %>
<%= image_tag'X.png',id:'x-button' %>

<div class="inputfields">
  <div class="toptext">Join Our Mailing List!</div>
  <div class="bottomtext">No Spam, Just Great Deals
    <%= f.text_field :name, class:"nameinput", placeholder:"name", id:"name-textfield",:'data-validation-length' =>"min1", :'data-validation'=>"length" %>
        <%= f.text_field :mail, class:"mailinput", placeholder:"e-mail address",id:"email-textfield", :'data-validation'=>"email" %><br>
            <input type="image" src="<%=asset_path('assets/JoinButton.png') %>" name="saveForm" class="joinbutton" id="join-button" />
            </div>

</div>

<% end %>
<script>
    $("#x-button").bind("click", function(){
        $('#popi').hide();
        $('#screen').remove();
    })  ;

    var CustomError ={badEmail :"Invalid Email",lengthTooShortStart:"Must be at least"}
    $.validate({language : CustomError});
</script>

app/views/pages/terms.html.erb
<div id="terms-wrapper">
  <div id="terms-paragraph">
    <div id="terms" class="Sabout">ABOUT US</div>
   <%= @record.saboutus %>
    <div id="terms" class="Stos">TERMS OF SERVICE</div>

    <h5>Payment</h5>
    <%= @record.payment %>

    <br><br>
    <h5>Shipping Policies</h5>
    <%= @record.shippingp %>

    <div id="terms" class="Spolicy">PURCHASE POLICY</div>
    <h5>Returns and Exchanges</h5>
    <%= @record.returnE %>


    <br><br>
    <h5>Cancellation</h5>
    <%= @record.canccelation %>

    <br><br>
    <h5>Complaints</h5>
    <%= @record.complaints %>


    <div id="terms" class="Scontant">CONTACT</div>
    <h5>Mail:</h5>
    <%= @record.iaddress %>
    <br><br>
    <h5>Phone:</h5>
    <%= @record.iphone %>
    <br><br>
    <h5>Email:</h5>
    <%= @record.imail %>    <br><br>

  </div>
</div>